// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd_AUb3d5Z9NSf4eMXK_iMGWOg7BFiaSQ',
    appId: '1:229566054768:web:14252bab2532fa7c4f8fb5',
    messagingSenderId: '229566054768',
    projectId: 'air-force-meter-app',
    authDomain: 'air-force-meter-app.firebaseapp.com',
    storageBucket: 'air-force-meter-app.appspot.com',
    measurementId: 'G-6CJRJ1GX94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmC67j0SilESX5NYcw8ocqubUXA-y87Q8',
    appId: '1:229566054768:android:ffd4bb5067192d1c4f8fb5',
    messagingSenderId: '229566054768',
    projectId: 'air-force-meter-app',
    storageBucket: 'air-force-meter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqeOi7mjqyedl1kqqQQ9XhCGq5XAX0nPc',
    appId: '1:229566054768:ios:e4695611f23afd8e4f8fb5',
    messagingSenderId: '229566054768',
    projectId: 'air-force-meter-app',
    storageBucket: 'air-force-meter-app.appspot.com',
    iosBundleId: 'com.example.intelligentMeterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqeOi7mjqyedl1kqqQQ9XhCGq5XAX0nPc',
    appId: '1:229566054768:ios:77fdb01fe61834a74f8fb5',
    messagingSenderId: '229566054768',
    projectId: 'air-force-meter-app',
    storageBucket: 'air-force-meter-app.appspot.com',
    iosBundleId: 'com.example.intelligentMeterApp.RunnerTests',
  );
}
